name: Test
on:
  push:
    branches:
      - '*'
      - '!master'

  pull_request:
    branches:
      - master

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.12.0'
      - name: Install dependencies
        run: |
          npm install
      - name: Test with jest
        run: |
          npm run test
